api_hash: 
api_key: ''
database:
  database: 
  password: 
  host: 
  user: 
disabled_cmd: ''
telegram:
  TOKEN: 
  admin_group: ''
  uid: ''
  channel_id: ''
  channel_name: ''
  document_group_id: ''
  name: ''
check_group_id:
  - 1012414645